name: Test ./demo with demofile.txt
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    name: Generate ./demofile.txt
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run sudo apt update
        run: sudo apt update -y

      - name: Install pip
        run: sudo apt install pip -y

      - name: Install Pillow
        run: |
          sudo pip install Pillow

      - name: Build ./demo
        run: |
          aclocal
          autoconf
          automake --add-missing
          ./configure
          make

      - name: Generate demofile.txt with sprites.py
        run: |
          python ./scripts/sprites.py s4c-file "./sample-sprites/alt-chest-animation" > ./demofile.txt && echo -e "\n\033[1;32mSuccess.\e[0m\n"

      - name: Run ./demo with demofile.txt
        run: |
          ./demo demofile.txt <<< cat "\n\n\n\n\n\n\n\n\n\n\n\n" && echo -e "\n\033[1;32mSuccess.\e[0m\n"

