name: Compile tex files to pdf
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Convert pdfs out of tex files
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Run sudo apt update
        run: sudo apt update -y
          
      - name: Install doxygen
        run: sudo apt install doxygen -y
          
      - name: Generate texfile
        run: |
          ls
          cd ./documentation && 
          echo "Switched dir" &&
          ls &&
          doxygen "s4c.doxyfile"

        
      - name: Compile texfile with make
        run: |
          ls &&
          cd ./documentation/latex &&
          make
          
      - name: Stat output
        run: |
          ls &&
          "stat ./documentation/docs.pdf$"
