name: Compile tex files to pdf
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Convert pdfs out of tex files
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Run sudo apt update
        run: sudo apt update -y
          
      - name: Install doxygen
        run: sudo apt install doxygen -y
                  
      - name: Install texlive
        run: sudo apt install texlive-latex-base -y
          
      - name: Generate tex
        run: |
          ls &&
          doxygen "./documentation/s4c.doxyfile"

        
      - name: Compile tex with make
        run: |
          ls &&
          echo -e "\ncd to ./latex\n"
          cd ./latex &&
          ls &&
          make && echo -e "\nDone\n"
          
      - name: Stat output
        run: |
          ls ./latex &&
          stat "./latex/refman.pdf"
