name: Compile tex files to pdf
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Convert pdfs out of tex files
    container:
      image: ghcr.io/csunibo/build-image:latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Run sudo apt update
        run: sudo apt update -y
          
      - name: Install doxygen
        run: sudo apt install doxygen -y
          
      - name: Generate texfile
        run: doxygen "documentation/s4c.doxyfile"

      - name: Change dir to documentation/latex/
        run: "cd documentation/latex"
        
      - name: Compile texfile
        run: ../../.github/workflows/rec "*\.tex$" "xelatex -pdf"
        
      - name: Stat output
        run: "stat docs.pdf$"
